### ISSUE TITLE
issue when starting the application

### ISSUE THREAD

**Issue by borisNG** [uuchat/uuchat#6]
hello ,
facing an issue when starting the program

Error: Cannot find module './htmlInterpolatePlugin'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/MacUser/Desktop/projects/consultingfly/mproj/uuchat/tools/webpack.config.prod.js:11:31)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/MacUser/Desktop/projects/consultingfly/mproj/uuchat/tools/build.js:10:16)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uuchat@0.2.1 start: `node tools/build.js && node index.js`
npm ERR! Exit status 1

**Comment by veerjainATgmail** [comment]
const HtmlInterpolatePlugin = require('interpolate-html-plugin');
npm install interpolate-html-plugin
